kind: "Role"
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: new-user
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: [ "get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: [
	"daemonsets",
	"deployments",
	"deployments/scale",
	"ingresses",
	"replicasets",
	"replicasets/scale",
	"replicationcontrollers/scale"
  ]
  verbs: [ "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: "RoleBinding"
metadata:
  name: new-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "Role"
  name: new-user
subjects:
- kind: ServiceAccount
  name: new-user
